urls.py
from xml.dom.minidom import Document
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # Rutas API

    path("postear", views.postear, name="postear"),
    path("posts/<int:pagina>", views.posts, name="posts"),
    path("perfil/<int:usuario>",  views.perfil, name="perfil"),
    path("seguir", views.seguir, name="seguir"),
    path("dejar_de_seguir", views.dejar_de_seguir, name="dejar_de_seguir"),
    path("like", views.like, name="like"),
    path("unlike", views.unlike, name="unlike"),
    path("verpost", views.verpost, name="ver_post"),   

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

models.py
from sqlite3 import Timestamp
from tkinter import CASCADE
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass    


class Siguiendo(models.Model):
    Seguido = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, related_name="UsuarioSeguidor")
    Seguidor = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, related_name="UsuarioSeguido")


class Post(models.Model):
    User = models.ForeignKey(User, on_delete= models.CASCADE, blank=False) 
    Texto = models.TextField(max_length=1024)
    Imagen = models.ImageField(upload_to='images/', blank=True)
    Likes = models.IntegerField(auto_created=True, default=0)
    Timestamp = models.DateTimeField(auto_now_add=True)
    
    def serialize(self):
        return{
            "id": self.id,
            "User": self.User.username,
            "User_id": self.User.pk,
            "Texto": self.Texto,
            "Likes": self.Likes,
            #"Imagen": self.Imagen,
            "Timestamp": self.Timestamp.strftime("%b %d %Y, %I:%M %p"),
        }

         

    def __str__(self) -> str:
        return f"{self.User}  {self.Timestamp} \n {self.Texto}" 

class Like(models.Model):
    Posteo = models.ForeignKey(Post, on_delete=models.CASCADE, blank=False)
    Usuario = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)

templates/network/error.html
{% extends "network/layout.html" %}

{% block body %}

<h3>Ha ocurrido un error</h3>

{%endblock%}

templates/network/index.html
{% extends "network/layout.html" %}

{% load static %}
{% block body %}
    {% if user.is_authenticated %}
    <h3 id="h3-bienvenido">Bienvenido, {{user.username}}</h3>
    <div id="div_user" hidden>{{user.id}}</div> 
    <div id="div-previo-post" hidden>-1</div>   
    <h4 id="h4-nuevo-editar">Nuevo Post</h4>
        <div id="nuevo-post">            
            <form id="form-nuevo-post" action="{% url 'postear' %}" method="post" enctype="multipart/form-data">       
                <div class="grupo-form">
                    <label for="id_Imagen">Imagen:</label>
                    <input type="file" name="Imagen" accept="image/*" id="newpost_Imagen">        
                </div>   
                <div class="grupo-form">
                    <label for="id_Texto">Texto:</label>
                    <textarea name="Texto" cols="40" rows="5" maxlength="1024" required id="newpost_Texto"></textarea>
                </div>
                <div class="grupo-form"> 
                    <input type="hidden" name="User" value={{user.id}} id="newpost_User">        
                </div>  
                <div class="grupo-form"> 
                    <input type="hidden" name="Likes" value=0 id="id_Likes">        
                </div>                
                    <input type="submit" value="Enviar">
            </form>        
        </div>
    {% endif %}

    <div id="perfil">
        <h1 id="nombre-perfil">Aqui vamos a ver el perfil</h1>
        <div id="div-seguir">
            <h6 id="yatesigue">Te está siguiendo</h6>
            <button type="button" class="btn btn-primary" id="follow-button">Seguir</button> 
            <button type="button" class="btn btn-primary" id="unfollow-button">Dejar de seguir</button>       
        </div>    
    </div>

    <div id="timeline" class="timeline-class">        
    </div>

    <nav aria-label="Navegacion-Paginas">
        <ul class="pagination">
          <li class="page-item" id="page-item-anterior"><a class="page-link" href="#">Anterior</a></li>
          <li class="page-item" id="page-item-1"><a class="page-link" href="#">1</a></li>
          <li class="page-item" id="page-item-2"><a class="page-link" href="#">2</a></li>
          <li class="page-item" id="page-item-3"><a class="page-link" href="#">3</a></li>
          <li class="page-item" id="page-item-siguiente"><a class="page-link" href="#">Siguiente</a></li>
        </ul>
    </nav>
    <div class="post1" style="display: none;">No se ve</div>

      
{% endblock %}


{% block script %}    
    <script src="{% static 'network/index.js' %}"></script>
{% endblock %}

templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'index' %}">Network</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" id="id_following" href="#">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}

            {%block script%}
            {%endblock%}
        </div>
    </body>
</html>

templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

templates/network/prueba.html
{% extends "network/layout.html" %}

{% block body %}

<h3>Guardamos exitosamente el post</h3>

{%endblock%}

templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}